### PR TITLE
Feature/inspec4alerts

### PR DESCRIPTION
**Pull request by imjoseangel**

### CODE REVIEW

**Comment by atomic111** [comment]
@imjoseangel thanks for the great improvement. but we have to wait for the chef answer about using inspec 4.0 (look at https://github.com/dev-sec/apache-baseline/pull/31), because they changed the license

**Comment by chris-rock** [comment]
We should also be aware that the change of attribute values is breaking older inspec versions. Until there is a clarification from Chef, we need to support InSpec 3.

**Comment by imjoseangel** [comment]
> We should also be aware that the change of attribute values is breaking older inspec versions. Until there is a clarification from Chef, we need to support InSpec 3.

Agree! Once confirmed, I can amend the PR if needed.

**Comment by chris-rock** [comment]
Last week I verified the values with latest version of InSpec 3. The use of value is fine as long as we update the minimum InSpec version to 3.4.1 in the readme (see https://github.com/inspec/inspec/blob/95ed2696e98181133cc586797d90e1ff777f79a4/CHANGELOG.md#v341-2019-01-29). Therefore we can merge this PR.

**Comment by imjoseangel** [comment]
Hey! Is it possible to merge this PR? Thanks!

**Pull request merged**
