### PR TITLE
Fixes comparisons when registry key data type are REG_SZ

### LINKED ISSUE #45: False Positives due to integers in strings
**Describe the bug**
Many Inspec tests are failing the test when Windows stores a numerical value as a string.

**Expected behavior**
Tests should pass when the expected value is either a number or string

**Actual behavior**
```
AllocateDASD
is expected to eq 
  Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }

    expected: 0
         got: "0"

    (compared using ==)
  # windows-baseline-master/controls/local_policies.rb:1094:in `block (3 levels) in load_with_context'
```

**OS / Environment**
Domain-joined Windows Server 2016/2019

**Inspec Version**
```
4.20.10
```

**Baseline Version**
```
2.1.4
```

**Additional context**

I believe the recommendation from Opscode is to use `cmp` instead of `eq`

### PR DESCRIPTION
**Pull request by imjoseangel**
Fixes #45 

Revised all the REG_SZ with integer values and changed to `cmp`.

Now returns are like:

```rb
✔  Registry Key XXX is expected to cmp <= 4
```

### CODE REVIEW

**Comment by kjake** [comment]
I agree that these changes solve #46

**Comment by imjoseangel** [comment]
@rndmh3ro @chris-rock Could you please have a look to this PR? Thank you!

**Comment by chris-rock** [comment]
Great improvements @imjoseangel and thank you @kjake for testing

**Comment by micheelengronne** [comment]
The improvments are now available in https://github.com/dev-sec/windows-baseline/releases/tag/2.1.6

**Pull request merged**
